
version: "3.7"
services:

  service_db:
    image: mariadb:latest
    container_name: service_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_EXTERNAL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
   
  atlc_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: atlc_phpmyadmin
    environment:
      PMA_HOST: service_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    restart: always
    depends_on:
      - service_db
    ports:
      - 3307:80
